language: node_js
node_js:
  - "0.10"
env:
  global:
    - GHPAGES=".gh-pages"
    - secure: "TiAOsFfGlvE+wwDoMxYxlMnbJ/ey0c1KsHYahTA78zu5aHVGksOsjKKfZTcrl7Eiup5KSLcpcD1FXDIpUGNggO1b1w/nt8SLI8X0qTRpgVUUHVVnGAuSeg1+TmoVUcM//RSJwTaQrzqQCyqJtGehumV2Y9DA7WSLywzWx/4bPMQ="
branches:
  only:
    - master
before_install:
  - "npm i coveralls grunt-cli"
before_script:
  - "./node_modules/grunt-cli/bin/grunt build"
script:
  - "npm test"
after_success:
  - "npm run coverage"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - "git config --global user.email \"travis@travis-ci.org\" && git config --global user.name \"travis-ci\""
  - "git clone --branch=gh-pages https://${GH_TOKEN}@github.com/webpro/jquery-evergreen.git $GHPAGES"
  - "cat $GHPAGES/index.yml README.md > $GHPAGES/index.md"
  - "rsync --recursive --delete dist/ $GHPAGES/dist/"
  - "rsync --recursive --delete test/ $GHPAGES/test/"
  - "rsync --recursive --delete benchmark/ $GHPAGES/benchmark/"
  - "rsync --recursive --delete coverage/lcov-report/ $GHPAGES/coverage/"
  - "cp coverage/coverage.json coverage/lcov.info $GHPAGES/coverage/"
  - "rm -rf $GHPAGES/doc && ./node_modules/groc/bin/groc --out=$GHPAGES/doc"
  - "cd .release/commonjs && ../../node_modules/plato/bin/plato -r -d ../../$GHPAGES/complexity --jshint ../../.jshintrc ."
  - "cd $TRAVIS_BUILD_DIR"
  - "grunt clean:release"
  - "cd $GHPAGES && git add --all && git commit -m \"Update all the things\" && git push -fq origin gh-pages > /dev/null"
  - "cd $TRAVIS_BUILD_DIR"
  - "rm -rf ./coverage $GHPAGES"
