language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
before_install:
  - "npm i coveralls grunt-cli"
script:
  - "./node_modules/grunt-cli/bin/grunt"
  - "npm run coverage"
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"
